### ISSUE TITLE
Manager a player profile

### ISSUE THREAD

**Issue by dimitar-st-atanasov** [Final-project-of-Team-5-Telerik-Academy/final_project_team_5#7]
- [x] Automatic creation – when creating a tournament, if a participant cannot be matched to an existing profile (**must**);

- [x] Manual creation – by admin or director (**should**);

- [x] Directors can edit any player profile if not linked to a user (**should**);

- [x] If linked to a user, only they can edit it (**should**);

**Comment by petar-georgievv** [comment]
Tasks are finished.
